Assuming unrestricted shared filesystem usage.
None
host: CARLOSs-MacBook-Pro.local
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
python_sorted        1
total                2

Select jobs to execute...
Execute 1 jobs...
[Thu Jul 17 15:22:20 2025]
localrule python_sorted:
    output: s3_presorted.txt
    jobid: 1
    reason: Missing output files: s3_presorted.txt
    resources: tmpdir=/var/folders/q3/5zmml3z16g93bd3gdlq6bftm0000gp/T
Traceback (most recent call last):

  File "/Users/russell/.local/share/mamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/Users/russell/.local/share/mamba/envs/snakemake_env/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /Users/russell/Code/snakehive/russell && /Users/russell/.local/share/mamba/envs/snakemake_env/bin/python3.11 -m snakemake --snakefile '/Users/russell/Code/snakehive/russell/step_3' --target-jobs 'python_sorted:' --allowed-rules python_sorted --cores 4 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers mtime params code software-env input --conda-frontend 'conda' --shared-fs-usage software-deployment storage-local-copies source-cache input-output persistence sources --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --latency-wait 5 --scheduler 'ilp' --local-storage-prefix base64//LnNuYWtlbWFrZS9zdG9yYWdl --scheduler-solver-path '/Users/russell/.local/share/mamba/envs/snakemake_env/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules host --mode 'subprocess' --local-groupid 'local'' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/russell/.local/share/mamba/envs/snakemake_env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/russell/.local/share/mamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/Users/russell/.local/share/mamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Thu Jul 17 15:22:21 2025]
Error in rule python_sorted:
    message: None
    jobid: 1
    output: s3_presorted.txt
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Thu Jul 17 15:22:21 2025]
Error in rule python_sorted:
    message: None
    jobid: 1
    output: s3_presorted.txt
Complete log(s): /Users/russell/Code/snakehive/russell/.snakemake/log/2025-07-17T152220.022569.snakemake.log
WorkflowError:
At least one job did not complete successfully.
